### ISSUE TITLE
Отзыв

### ISSUE THREAD

**Issue by bsurai** [BruLex/script-languages-labs#2]
Понравилось:
- лабораторные в отделных ветках
- использование npx

### Лабораторная 1
\+ работает Hello World
\+ есть .gitignore
\+ тесты работают
\+ dotenv работает

\- jest и supertest должны находиться в devDpendencies

**Comment by bsurai** [comment]
### Лабораторная 2
\+ работает правильно
\+ тест nock работает

#### Легкие замечания
\- лишние зависимости в package.json - `factory-girl`, `mysql2`, `sequelize`, `child_process`. Понимаю, что они попали из других лабораторных. Но на практике лишних пакетов надо избегать.
\- jest и supertest должны находиться в devDpendencies
\- в `app.listen()` можно не указывать IP
\- экспорт в `api.service.js` можно было написать проще
вместо 
```js
module.exports = {
    makeHttpGetRequest: makeHttpGetRequest
};
```
написать
```js
module.exports = { makeHttpGetRequest };
```
Это фича из ES6. Если свойство объекта и переменная совпадают по имени, то можно опускать присваивание через двоеточие.

#### Важные замечания
\- В `proxy` перепутано понимание какие слои для чего нужны. Обработка запроса должна проходить по слоям в таком порядке `routes => services (business) => clients`. `clients` должен отсылать запросы на приложение `api`. Сейчас реализован порядок `routes => clients => services` и `services` отсылает запросы на приложение `api`.

\- По структуре подкаталогов в репозитории. Предложенный вариант работает и может применяться на практике. Но для больших систем лучше сделать по-другому.

Возможно, этому надо было уделить больше внимания. По факту, мы создаем `монорепу` - когда много приложений находятся в одном репозитории. На пример у Google такая монорепа просто громадная. 
Каждое приложение в монорепе может независимо деплоиться и масштабироваться. Поэтому  важно, чтобы код этих приложений не пересекался. Конфигурации приложений в монорепе тоже не должны пересекаться. Желательная структура репозитория выглядит так:
```
repo root
|- api
|   |- node_modules
|   |- app.js
|   |- config.js
|   |- server.js
|   |- server.spec.js
|   |- gitignore
|   |- package.json
|
|- proxy
|    |- node_modules
|    |- clients
|    |- services
|    |- routes
|    |- config.js
|    |- app.js
|    |- server.js
|    |- gitignore
|    |- package.json
|
|- package.json
|- скрипты для управления монорепой
```
В корне монорепы могут находиться:
- package.json с описанием проекта 
- дополнительные модули, скрипты, библиотеки, которые либо используются разными приложениями, либо помогают управлять содержимым монорепы.

**Comment by brulex** [comment]
> - jest и supertest должны находиться в devDpendencies

Yep, you are right, missed this. But here not code review, here just labs, so ¯\_(ツ)_/¯

**Comment by brulex** [comment]
> - лишние зависимости в package.json - `factory-girl`, `mysql2`, `sequelize`, `child_process`. Понимаю, что они попали из других лабораторных. Но на практике лишних пакетов надо избегать.

Yes, absolutely right. It happened when I rebasing some branches and these things got here.

> - в `app.listen()` можно не указывать IP

Not agree, it could be helpful if we don't need to serve our server globally (0.0.0.0)

> - экспорт в `api.service.js` можно было написать проще
> вместо
> 
> ```
> module.exports = {
>     makeHttpGetRequest: makeHttpGetRequest
> };
> ```
> 
> написать
> 
> ```
> module.exports = { makeHttpGetRequest };
> ```
> 
> Это фича из ES6. Если свойство объекта и переменная совпадают по имени, то можно опускать присваивание через двоеточие.

Yes, I know about this, but such things is more like to codeStyle and all of such things need to cover with linter which will find and show this things and fix it in case if rule have autofixer :)

**Comment by brulex** [comment]
> #### Важные замечания
> - В `proxy` перепутано понимание какие слои для чего нужны. Обработка запроса должна проходить по слоям в таком порядке `routes => services (business) => clients`. `clients` должен отсылать запросы на приложение `api`. Сейчас реализован порядок `routes => clients => services` и `services` отсылает запросы на приложение `api`.

Maybe we confuse the concepts, in lectures I dont here noting about this things and when I ask you directly you did not answer this question, therefore, I relied on my development experience. I understand next: **Service** is set of methods which do some work, call api methods in generic for, transfer data, save file etc. But **Client** this is some like entity which contain only methods which belongs to specific area, in our case api which know that somewhere we have entrypoint with '/', in feature it would be /fetch_files, /get_logs etc. + we could have another client e.g. payPalProcessor with next methods: authorize, generateInvoice etc. and both clients will use one service which make http calls.

**Comment by bsurai** [comment]
### Лабораторная 3
\+ работает

- тут наверное опечатка, stderr должно пайпиться в stderr
https://github.com/BruLex/script-languages-labs/blob/0552c3bc37957300fff3bf34383786b12ca63009/worker.js#L5

- вместо 
https://github.com/BruLex/script-languages-labs/blob/0552c3bc37957300fff3bf34383786b12ca63009/master.js#L2

можно импортировать только то, что будем использовать
```js
const { spawn }  = require('child_process');
const { createWriteStream } = require("fs");
```

**Comment by bsurai** [comment]
> в app.listen() можно не указывать IP
Not agree, it could be helpful if we don't need to serve our server globally (0.0.0.0)

Ваше право. На практике не видел, чтобы это использовалось.

**Comment by bsurai** [comment]
>> В proxy перепутано понимание какие слои для чего нужны. Обработка запроса должна проходить по слоям в таком порядке routes => services (business) => clients. clients должен отсылать запросы на приложение api. Сейчас реализован порядок routes => clients => services и services отсылает запросы на приложение api.

>Maybe we confuse the concepts, in lectures I dont here noting about this things and when I ask you directly you did not answer this question, therefore, I relied on my development experience. I understand next: Service is set of methods which do some work, call api methods in generic for, transfer data, save file etc. But Client this is some like entity which contain only methods which belongs to specific area, in our case api which know that somewhere we have entrypoint with '/', in feature it would be /fetch_files, /get_logs etc. + we could have another client e.g. payPalProcessor with next methods: authorize, generateInvoice etc. and both clients will use one service which make http calls.

- На лекции это говорилось и даже была схема с 3-мя слоями приложения. 
- После лекции вы спрашивали про концепцию слоев. И я ответил то же, что и сейчас. Может быть мы друг друга не поняли.
- то, что вы назвали `services`, это просто `axios`. И да, клиент к разным web сервисам использует axios (или fetch, request). Это просто либы с NPM.
- Инетересно где вы взяли такое представление о сервисах. Если можете, скиньте  ссылку.
- Вы пишете про `payPalProcessor`, как про `specific area` и поэтому у вас это клиент. Как бы вы организовали код по слоям, если при получении запроса нужно: сначала выполнить проверку в своей БД, отправить на PayPal, отправить на SalesForce, сохранить статус в БД? Как бы вы назвали слой, который оперирует разными клиентами?

**Comment by brulex** [comment]
> * На лекции это говорилось и даже была схема с 3-мя слоями приложения.
> * После лекции вы спрашивали про концепцию слоев. И я ответил то же, что и сейчас. Может быть мы друг друга не поняли.

On lecture you just say that this is can be 3 layers, but without normal examples + everything was very vague.

> * то, что вы назвали `services`, это просто `axios`. И да, клиент к разным web сервисам использует axios (или fetch, request). Это просто либы с NPM.

In example which you provide in labs, yes, it is only 'axios', but we can complicate the logic. For example: we want to log all request to any api, for this we can defined logger there + add error handler with specific logic. After this, it will be not only 'axios'.

> * Инетересно где вы взяли такое представление о сервисах. Если можете, скиньте  ссылку.

I'm angular developer and knowledge about service I take from angular specification. https://angular.io/guide/architecture-services

> * Вы пишете про `payPalProcessor`, как про `specific area` и поэтому у вас это клиент. Как бы вы организовали код по слоям, если при получении запроса нужно: сначала выполнить проверку в своей БД, отправить на PayPal, отправить на SalesForce, сохранить статус в БД? Как бы вы назвали слой, который оперирует разными клиентами?

In you case, I will done next, in route I first make PayPal call, after this make SalesForce call , inside each clients will be implemented checks/logging/executing api calls.

P.s. We can name things as we want, but each module must do one thing (single responsibility).
